apiVersion: v2

name: minio-operator

description: |-
  A Helm chart for deploying the Minio operator: the official Kubernetes operator for deploying MINIO cluster.

#home: https://github.com/elastic/cloud-on-k8s

type: application

version: 2.0.9-bb.2

appVersion: 2.0.9

kubeVersion: ">=1.12.0-0"

keywords:
  - Minio
  - Operator

maintainers:
  - name:
    email:

dependencies:
