apiVersion: v2
description: A Helm chart for MinIO Operator
name: minio-operator
version: 7.0.1-bb.2
appVersion: v7.0.1
keywords:
  - storage
  - object-storage
  - S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
  - https://github.com/minio/operator
maintainers:
  - name: MinIO, Inc
    email: dev@minio.io
type: application
dependencies:
  - name: minio-operator-crds
    version: "v7.0.0"
    condition: installCRDs
    repository: "file://minio-operator-crds"
  - name: gluon
    version: 0.5.12
    repository: oci://registry1.dso.mil/bigbang
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/applicationVersions: |
    - Minio Operator: v7.0.1
  helm.sh/images: |
    - name: operator
      image: registry1.dso.mil/ironbank/opensource/minio/operator:v7.0.1
