apiVersion: v2
description: A Helm chart for MinIO Operator
name: minio-operator
version: 7.1.1-bb.1
appVersion: v7.1.1
keywords:
  - storage
  - object-storage
  - S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
  - https://github.com/minio/operator
maintainers:
  - name: MinIO, Inc
    email: dev@minio.io
type: application
dependencies:
  - name: gluon
    version: 0.5.12
    repository: oci://registry1.dso.mil/bigbang
  - name: operator
    version: 7.1.1
    repository: https://operator.min.io
    alias: "upstream"
  
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/applicationVersions: | 
    - Minio Operator: v7.1.1
  helm.sh/images: |
    - name: operator
      image: registry1.dso.mil/ironbank/opensource/minio/operator:v7.1.1
