apiVersion: v2
description: A Helm chart for MinIO Operator
name: minio-operator
version: 4.5.4-bb.0
appVersion: v4.5.4
keywords:
  - storage
  - object-storage
  - S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
  - https://github.com/minio/operator
maintainers:
  - name: MinIO, Inc
    email: dev@minio.io
type: application
dependencies:
  - name: minio-operator-crds
    version: "4.5.3"
    condition: installCRDs
    repository: "file://minio-operator-crds"
annotations:
  bigbang.dev/applicationVersions: |
    - Minio Operator: v4.5.4
