apiVersion: v2
description: A Helm chart for MinIO Operator
name: minio-operator
version: 4.5.8-bb.1
appVersion: v4.5.8
keywords:
  - storage
  - object-storage
  - S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
  - https://github.com/minio/operator
maintainers:
  - name: MinIO, Inc
    email: dev@minio.io
type: application
dependencies:
  - name: minio-operator-crds
    version: "4.5.8"
    condition: installCRDs
    repository: "file://minio-operator-crds"
annotations:
  bigbang.dev/applicationVersions: |
    - Minio Operator: v4.5.8
  helm.sh/images: |
    - name: operator
      image: registry1.dso.mil/ironbank/opensource/minio/operator:v4.5.8
    - name: console
      condition: console.enabled
      image: registry1.dso.mil/ironbank/opensource/minio/console:v0.25.0
