{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-instance-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    # Allow to all NS to support tenant use of operator
    - namespaceSelector: {}
    ports:
    - port: 9000
      protocol: TCP
{{- end }}
