{{- if and .Values.networkPolicies.enabled .Values.bbtests.enabled  }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-test-console
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
    ports:
    - port: 9090
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}