apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio-operator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "minio-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minio-operator.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      serviceAccountName: {{ include "minio-operator.serviceAccountName" . }}
    {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          env:
          - name: CLUSTER_DOMAIN
            value: {{ .Values.operator.clusterDomain }}
          - name: WATCHED_NAMESPACE
            value: {{ .Values.operator.nsToWatch }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
