apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
    {{- if .Values.operator.podLabels }}
    {{- tpl ( toYaml .Values.operator.podLabels ) . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
  {{- include "minio-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minio-operator.labels" . | nindent 8 }}
        {{- include "minio-operator.selectorLabels" . | nindent 8 }}
        {{- if .Values.operator.podLabels }}
        {{- tpl ( toYaml .Values.operator.podLabels ) . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: minio-operator
      {{- with .Values.operator.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            - "controller"
          {{- with .Values.operator.env }}
          env:
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.operator.sidecarImage }}
          - name: "OPERATOR_SIDECAR_IMAGE"
            value: "{{ .Values.operator.sidecarImage.repository }}:{{ .Values.operator.sidecarImage.digest | default .Values.operator.sidecarImage.tag }}"
          {{- end }}
          resources: {{- toYaml .Values.operator.resources | nindent 12 }}
          securityContext:
          {{- with .Values.operator.containerSecurityContext }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.operator.initContainers }}
      initContainers:
      {{- toYaml . | nindent 8 }}
      {{- end}}
      {{- with .Values.operator.runtimeClassName }}
      runtimeClassName:
      {{- toYaml . | nindent 8 }}
  {{- end }}
