{{- if and .Values.istio.enabled .Values.istio.console.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "minio-operator.fullname" . }}-console
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "minio-operator.fullname" . }}
    {{- include "minio-operator.labels" . | nindent 4 }}
  {{- if .Values.istio.console.labels }}
    {{ toYaml .Values.istio.console.labels | indent 4 }}
  {{- end }}
  {{- if .Values.istio.console.annotations }}
  annotations:
    {{ toYaml .Values.istio.console.annotations | indent 2 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.console.gateways }}
  - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.console.hosts }}
  - {{ tpl . $}}
  {{- end }}
  http:
    - route:
      - destination:
          host: console.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 9090
{{ end }}
