{{- if .Values.istio.enabled }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: minio-operator-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      {{- include "minio-operator.selectorLabels" . | nindent 6 }}
  {{- if eq .Values.istio.mtls.mode "STRICT" }}
  # Operator receives traffic from kube-apiserver
  portLevelMtls:
    "4222":
      mode: PERMISSIVE
  {{- end }}
{{- end }}