apiVersion: v2
description: A Helm chart for MinIO Operator CRD deployment
name: minio-operator-crds
version: "5.0.5"
appVersion: "5.0.5"
kubeVersion: ">=1.19.0-0"
keywords:
  - Minio
  - storage
  - object-storage
  - S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
  - https://github.com/minio/operator
maintainers:
  - name: MinIO, Inc
    email: dev@minio.io
type: application
